version: '3.1'

services:

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: pool-notifier
      MYSQL_USER: pool-notifier
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
  mosquitto:
     image: eclipse-mosquitto
     ports:
       - 1883:1883