---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    netunus: backend-service-account
  name: netunus-backend-service-account
---
apiVersion: v1
kind: Service
metadata:
  labels:
    netunus: backend
  name: netunus-backend-service
spec:
  ports:
    port: 8080
  selector:
    netunus: backend-deployment
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    netunus: backend-deployment
  name: netunus-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      netunus: backend
  template:
    metadata:
      labels:
        netunus: backend
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: konstantin/netunus:1.0.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: backend
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      serviceAccount: netunus
