---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  labels:
    app: "netunus"
    version: "1.0.0-SNAPSHOT"
    group: "konstantin"
  name: "netunus"
---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "netunus"
    version: "1.0.0-SNAPSHOT"
    group: "konstantin"
  name: "netunus"
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: "netunus"
    version: "1.0.0-SNAPSHOT"
    group: "konstantin"
  type: LoadBalancer
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "netunus"
    version: "1.0.0-SNAPSHOT"
    group: "konstantin"
  name: "netunus"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "netunus"
      version: "1.0.0-SNAPSHOT"
      group: "konstantin"
  template:
    metadata:
      labels:
        app: "netunus"
        version: "1.0.0-SNAPSHOT"
        group: "konstantin"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "konstantin/netunus:1.0.0-SNAPSHOT"
        imagePullPolicy: "IfNotPresent"
        name: "netunus"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
      serviceAccount: "netunus"
