apiVersion: v1
kind: Service
metadata:
  labels:
    netunus: database-service
  name: netunus-database-service
spec:
  ports:
    - port: 3306
  selector:
    netunus: database-service
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    netunus: db-claim0
  name: db-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netunus-database-deployment
  labels:
    netunus: database-deployment
spec:
  selector:
    matchLabels:
      netunus: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        netunus: database
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: "pool-notifier"
        - name: MYSQL_PASSWORD
          value: "secret"
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "yes"
        - name: MYSQL_USER
          value: "pool-notifier"
        image: mariadb:10.3.22-bionic
        name: database
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-claim0
      volumes:
      - name: db-claim0
        persistentVolumeClaim:
          claimName: db-claim0
