apiVersion: v1
kind: Service
metadata:
  name: netunus-frontend-service
  labels:
    netunus: frontend
spec:
  ports:
    - port: 80
  selector:
    netunus: frontend-deployment
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netunus-frontend-deployment
  labels:
    netunus: frontend-deployment
spec:
  selector:
    matchLabels:
      netunus: frontend
  template:
    metadata:
      labels:
        netunus: frontend
    spec:
      containers:
      - image: nginx:1.18.0
        name: frontend
        ports:
        - containerPort: 80
          name: frontend
