@startuml
left to right direction
actor Poolbesitzer
actor Poolsafer
rectangle NETUNUS{
    Poolbesitzer -- (Bekommt Benachrichtigung)
    Poolbesitzer -- (Deaktiviert Alarm)
    Poolbesitzer -- (Deaktiviert zeitgesteuert das Überwachungssystem)
    Poolbesitzer -- (Betrachtet vergangene Auslöser)
    (Bekommt Benachrichtigung) .> (Auslösen des Alarms) : <<extends>>
    (Deaktiviert Alarm) -- Poolbenutzer
    (Deaktiviert zeitgesteuert das Überwachungssystem) -- Poolbenutzer
    (Auslösen des Alarms) -- Poolbenutzer
}
@enduml